import tkinter as tk
from tkinter import scrolledtext, ttk

# Dictionary to store help texts in multiple languages
HELP_TEXTS = {
    "edit_helper": {
        "de": (
            "=== Hilfe – Funktionsbeschreibung mit Beispielen ===\n\n"
            "🚀 **Allgemeine Optionen**\n"
            "• **Onefile**\n"
            "  Alles in einer einzigen ausführbaren EXE-Datei bündeln (praktisch für einfache Verteilung).\n"
            "• **Konsole**\n"
            "  Lässt beim Ausführen das Konsolenfenster sichtbar (gut für Debug-Ausgaben).\n"
            "• **Fenster-Modus**\n"
            "  Anwendung ohne sichtbares Konsolenfenster starten (z.B. für grafische Benutzeroberflächen).\n"
            "• **Use PyArmor**\n"
            "  Aktiviert Code-Verschleierung für zusätzlichen Schutz (optional).\n\n"
            "📦 **Felder:**\n"
            "• **Name**\n"
            "  Name des Projekts oder der ausführbaren Datei.\n"
            "  Eingabebeispiel:\n"
            "  MeinBackupTool\n\n"
            "• **Script**\n"
            "  Pfad zum Python-Skript, das kompiliert werden soll.\n"
            "  Eingabebeispiel:\n"
            "  C:/Projekte/backupTool/backupWizard.py\n\n"
            "• **Ausgabeordner**\n"
            "  Zielordner für die erstellte EXE-Datei.\n"
            "  Eingabebeispiel:\n"
            "  C:/Projekte/backupTool/dist\n\n"
            "• **Iconpfad**\n"
            "  Pfad zu einer .ico-Datei als Programmsymbol.\n"
            "  Eingabebeispiel:\n"
            "  C:/Projekte/backupTool/assets/appicon.ico\n\n"
            "• **Add-Data**\n"
            "  Zusätzliche Dateien oder Ordner, die mit der EXE gebündelt werden sollen.\n"
            "  Format: Quellpfad:Zielpfad (bei mehreren Einträgen mit Semikolon trennen).\n"
            "  Eingabebeispiel:\n"
            "  C:/Daten/config.ini:config;C:/Daten/bilder:assets/bilder\n\n"
            "• **Hidden Imports**\n"
            "  Python-Module, die PyInstaller eventuell nicht automatisch erkennt.\n"
            "  Eingabebeispiel:\n"
            "  requests,lxml,custom_module\n\n"
            "• **Version-Datei**\n"
            "  Pfad zu einer Datei mit Versionsinformationen.\n"
            "  Eingabebeispiel:\n"
            "  C:/Projekte/backupTool/version.txt\n\n"
            "• **Runtime Hook**\n"
            "  Pfad zu einem Python-Skript, das beim Start der Anwendung ausgeführt wird.\n"
            "  Eingabebeispiel:\n"
            "  C:/Projekte/backupTool/startup_hook.py\n\n"
            "• **Splash-Bild**\n"
            "  Pfad zu einem Bild, das beim Start angezeigt wird.\n"
            "  Eingabebeispiel:\n"
            "  C:/Projekte/backupTool/splashscreen.png\n\n"
            "• **Spec-Datei**\n"
            "  Pfad zu einer .spec-Datei für individuelle PyInstaller-Build-Konfigurationen.\n"
            "  Eingabebeispiel:\n"
            "  C:/Projekte/backupTool/backupWizard.spec\n\n"
            "⚙️ **Erweiterte Optionen:**\n"
            "• **UPX**: Aktiviert Komprimierung der EXE (verkleinert die Dateigröße).\n"
            "• **Debug**: Aktiviert Debug-Modus (hilfreich für Fehlersuche).\n"
            "• **Clean**: Alte Build-Dateien vor dem Erstellen löschen.\n"
            "• **Strip**: Entfernt Debug-Symbole, verkleinert die EXE.\n"
            "• **Ohne Runtime Key**: Erstellt die EXE ohne Laufzeit-Schlüssel.\n"
            "• **Tcl deaktivieren**: Deaktiviert Tcl/Tk-Support (z.B. wenn nicht benötigt).\n\n"
            "📝 **Weitere Optionen:**\n"
            "Hier können zusätzliche PyInstaller-Parameter direkt eingetragen werden.\n"
            "Eingabebeispiel:\n"
            "--add-binary=\"C:/libs/extra.dll;extra.dll\" --hidden-import=asyncio\n\n"
            "✅ **Tipps für erfolgreiche Eingaben:**\n"
            "• **Add-Data**: Absolute Pfade verwenden und sicherstellen, dass Dateien/Ordner existieren.\n"
            "• **Hidden Imports**: Module ohne Leerzeichen, nur durch Kommas trennen.\n"
            "  Beispiel:\n"
            "  numpy,requests,flask\n"
            "• **Icon, Version, Splash**: Dateien müssen existieren und korrekt angegeben werden.\n"
            "• **Ausgabeordner**: Ordner muss existieren oder automatisch erstellt werden können.\n"
            "• **Script**: Muss ein gültiges Python-Skript sein.\n\n"
            "🖱️ **Schaltflächen:**\n"
            "• **Speichern**: Speichert die aktuellen Einstellungen des Projekts.\n"
            "• **Abbrechen**: Schließt das Editor-Fenster ohne Speichern.\n\n\n"
            "🔒 **PyArmor-Optionen (Schutz & Verschleierung)**\n"
            "• **--obf-code <0|1|2>**: Steuert die Obfuskationsebene des Codes (0=keine, 1=normal, 2=hoch).\n"
            "• **--obf-module <0|1>**: Obfuskiert das gesamte Modul (1=aktiviert).\n"
            "• **--mix-str**: Verschlüsselt Zeichenketten im Code.\n"
            "• **--no-wrap**: Deaktiviert den Standard-Wrap-Modus.\n"
            "• **--private**: Aktiviert den privaten Modus (Einschränkung interner Einblicke).\n"
            "• **--restrict**: Aktiviert restriktiven Modus für das Paket.\n"
            "• **--assert-import**: Sicherstellt, dass importierte Module obfuskiert sind.\n"
            "• **--assert-call**: Sicherstellt, dass aufgerufene Funktionen obfuskiert sind.\n"
            "• **--platform NAME**: Zielplattform angeben (z.B. windows.x86_64).\n"
            "• **--use-runtime PATH**: Laufzeitpaket von angegebenem Pfad verwenden.\n"
            "• **--outer**: Verwendet externen Laufzeitschlüssel für mehr Sicherheit.\n"
            "• **--expired DATE**: Ablaufdatum setzen (z.B. 2025-12-31).\n"
            "• **--period N**: Überprüfungsintervall für Laufzeitschlüssel.\n"
            "• **--bind-device DEV**: Bindet das Skript an bestimmte Geräte (z.B. MAC-Adresse).\n"
            "• **--pack <onefile|onedir|NAME.spec>**: Verpackt das obfuskierte Projekt.\n"
            "• **-r, --recursive**: Verschlüsselt Dateien in Unterordnern rekursiv.\n"
            "• **-O PATH**: Ausgabeverzeichnis festlegen.\n"
            "• **--exclude PATTERN**: Dateien oder Pfade von Obfuskation ausschließen.\n\n"
            "Diese Optionen können in den **PyArmor-Optionen** im Editor direkt angegeben werden.\n\n"
            "💡 **Beispiel-Eingabe:**\n"
            " --platform windows.x86_64 --pack onefile --expired 2025-12-31 --bind-device 08:00:27:12:34:56\n"
            "🖱️ **Schaltflächen:**\n"
            "• **Speichern**: Speichert die aktuellen Einstellungen des Projekts.\n"
            "• **Abbrechen**: Schließt das Editor-Fenster ohne Speichern.\n"
        ),
        "en": (
            "=== Help – Function Description with Examples ===\n\n"
            "🚀 **General Options**\n"
            "• **Onefile**\n"
            "  Bundle everything into a single executable EXE file (convenient for easy distribution).\n"
            "• **Console**\n"
            "  Keep the console window visible during execution (useful for debug outputs).\n"
            "• **Windowed Mode**\n"
            "  Launch the application without a visible console window (e.g., for graphical user interfaces).\n"
            "• **Use PyArmor**\n"
            "  Enable code obfuscation for additional protection (optional).\n\n"
            "📦 **Fields:**\n"
            "• **Name**\n"
            "  Name of the project or executable file.\n"
            "  Example input:\n"
            "  MyBackupTool\n\n"
            "• **Script**\n"
            "  Path to the Python script to be compiled.\n"
            "  Example input:\n"
            "  C:/Projects/backupTool/backupWizard.py\n\n"
            "• **Output Folder**\n"
            "  Destination folder for the created EXE file.\n"
            "  Example input:\n"
            "  C:/Projects/backupTool/dist\n\n"
            "• **Icon Path**\n"
            "  Path to an .ico file for the program icon.\n"
            "  Example input:\n"
            "  C:/Projects/backupTool/assets/appicon.ico\n\n"
            "• **Add-Data**\n"
            "  Additional files or folders to be bundled with the EXE.\n"
            "  Format: SourcePath:TargetPath (separate multiple entries with semicolons).\n"
            "  Example input:\n"
            "  C:/Data/config.ini:config;C:/Data/images:assets/images\n\n"
            "• **Hidden Imports**\n"
            "  Python modules that PyInstaller might not automatically detect.\n"
            "  Example input:\n"
            "  requests,lxml,custom_module\n\n"
            "• **Version File**\n"
            "  Path to a file containing version information.\n"
            "  Example input:\n"
            "  C:/Projects/backupTool/version.txt\n\n"
            "• **Runtime Hook**\n"
            "  Path to a Python script executed at application startup.\n"
            "  Example input:\n"
            "  C:/Projects/backupTool/startup_hook.py\n\n"
            "• **Splash Image**\n"
            "  Path to an image displayed at startup.\n"
            "  Example input:\n"
            "  C:/Projects/backupTool/splashscreen.png\n\n"
            "• **Spec File**\n"
            "  Path to a .spec file for custom PyInstaller build configurations.\n"
            "  Example input:\n"
            "  C:/Projects/backupTool/backupWizard.spec\n\n"
            "⚙️ **Advanced Options:**\n"
            "• **UPX**: Enables compression of the EXE (reduces file size).\n"
            "• **Debug**: Enables debug mode (helpful for troubleshooting).\n"
            "• **Clean**: Deletes old build files before creating new ones.\n"
            "• **Strip**: Removes debug symbols, reducing EXE size.\n"
            "• **No Runtime Key**: Creates the EXE without a runtime key.\n"
            "• **Disable Tcl**: Disables Tcl/Tk support (e.g., if not needed).\n\n"
            "📝 **Additional Options:**\n"
            "Enter additional PyInstaller parameters directly here.\n"
            "Example input:\n"
            "--add-binary=\"C:/libs/extra.dll;extra.dll\" --hidden-import=asyncio\n\n"
            "✅ **Tips for Successful Inputs:**\n"
            "• **Add-Data**: Use absolute paths and ensure files/folders exist.\n"
            "• **Hidden Imports**: List modules without spaces, separated by commas.\n"
            "  Example:\n"
            "  numpy,requests,flask\n"
            "• **Icon, Version, Splash**: Files must exist and be correctly specified.\n"
            "• **Output Folder**: Must exist or be creatable automatically.\n"
            "• **Script**: Must be a valid Python script.\n\n"
            "🖱️ **Buttons:**\n"
            "• **Save**: Saves the current project settings.\n"
            "• **Cancel**: Closes the editor window without saving.\n\n\n"
            "🔒 **PyArmor Options (Protection & Obfuscation)**\n"
            "• **--obf-code <0|1|2>**: Controls code obfuscation level (0=none, 1=normal, 2=high).\n"
            "• **--obf-module <0|1>**: Obfuscates the entire module (1=enabled).\n"
            "• **--mix-str**: Encrypts strings in the code.\n"
            "• **--no-wrap**: Disables the default wrap mode.\n"
            "• **--private**: Enables private mode (restricts internal insights).\n"
            "• **--restrict**: Enables restrictive mode for the package.\n"
            "• **--assert-import**: Ensures imported modules are obfuscated.\n"
            "• **--assert-call**: Ensures called functions are obfuscated.\n"
            "• **--platform NAME**: Specify target platform (e.g., windows.x86_64).\n"
            "• **--use-runtime PATH**: Use runtime package from the specified path.\n"
            "• **--outer**: Uses an external runtime key for added security.\n"
            "• **--expired DATE**: Set expiration date (e.g., 2025-12-31).\n"
            "• **--period N**: Verification interval for runtime key.\n"
            "• **--bind-device DEV**: Binds the script to specific devices (e.g., MAC address).\n"
            "• **--pack <onefile|onedir|NAME.spec>**: Packs the obfuscated project.\n"
            "• **-r, --recursive**: Encrypts files in subdirectories recursively.\n"
            "• **-O PATH**: Specify output directory.\n"
            "• **--exclude PATTERN**: Exclude files or paths from obfuscation.\n\n"
            "These options can be specified directly in the **PyArmor Options** in the editor.\n\n"
            "💡 **Example Input:**\n"
            " --platform windows.x86_64 --pack onefile --expired 2025-12-31 --bind-device 08:00:27:12:34:56\n"
            "🖱️ **Buttons:**\n"
            "• **Save**: Saves the current project settings.\n"
            "• **Cancel**: Closes the editor window without saving.\n"
        ),
        "fr": (
            "=== Aide – Description des fonctions avec exemples ===\n\n"
            "🚀 **Options générales**\n"
            "• **Onefile**\n"
            "  Regroupe tout dans un seul fichier exécutable EXE (pratique pour une distribution simple).\n"
            "• **Console**\n"
            "  Affiche la fenêtre de console lors de l'exécution (utile pour les sorties de débogage).\n"
            "• **Mode Fenêtré**\n"
            "  Lance l'application sans fenêtre de console visible (par ex. pour les interfaces graphiques).\n"
            "• **Utiliser PyArmor**\n"
            "  Active l'obfuscation de code pour une protection supplémentaire (optionnel).\n\n"
            "📦 **Champs :**\n"
            "• **Nom**\n"
            "  Nom du projet ou du fichier exécutable.\n"
            "  Exemple de saisie :\n"
            "  MonOutilDeSauvegarde\n\n"
            "• **Script**\n"
            "  Chemin vers le script Python à compiler.\n"
            "  Exemple de saisie :\n"
            "  C:/Projets/backupTool/backupWizard.py\n\n"
            "• **Dossier de sortie**\n"
            "  Dossier cible pour le fichier EXE créé.\n"
            "  Exemple de saisie :\n"
            "  C:/Projets/backupTool/dist\n\n"
            "• **Chemin de l'icône**\n"
            "  Chemin vers un fichier .ico pour l'icône du programme.\n"
            "  Exemple de saisie :\n"
            "  C:/Projets/backupTool/assets/appicon.ico\n\n"
            "• **Ajout de données**\n"
            "  Fichiers ou dossiers supplémentaires à inclure dans l'EXE.\n"
            "  Format : CheminSource:CheminCible (séparer les entrées multiples par des points-virgules).\n"
            "  Exemple de saisie :\n"
            "  C:/Donnees/config.ini:config;C:/Donnees/images:assets/images\n\n"
            "• **Imports cachés**\n"
            "  Modules Python que PyInstaller pourrait ne pas détecter automatiquement.\n"
            "  Exemple de saisie :\n"
            "  requests,lxml,mon_module_personnalise\n\n"
            "• **Fichier de version**\n"
            "  Chemin vers un fichier contenant des informations de version.\n"
            "  Exemple de saisie :\n"
            "  C:/Projets/backupTool/version.txt\n\n"
            "• **Hook d'exécution**\n"
            "  Chemin vers un script Python exécuté au démarrage de l'application.\n"
            "  Exemple de saisie :\n"
            "  C:/Projets/backupTool/startup_hook.py\n\n"
            "• **Image de démarrage**\n"
            "  Chemin vers une image affichée au démarrage.\n"
            "  Exemple de saisie :\n"
            "  C:/Projets/backupTool/splashscreen.png\n\n"
            "• **Fichier Spec**\n"
            "  Chemin vers un fichier .spec pour des configurations de build PyInstaller personnalisées.\n"
            "  Exemple de saisie :\n"
            "  C:/Projets/backupTool/backupWizard.spec\n\n"
            "⚙️ **Options avancées :**\n"
            "• **UPX** : Active la compression de l'EXE (réduit la taille du fichier).\n"
            "• **Débogage** : Active le mode débogage (utile pour résoudre les erreurs).\n"
            "• **Nettoyer** : Supprime les anciens fichiers de build avant la création.\n"
            "• **Strip** : Supprime les symboles de débogage, réduisant la taille de l'EXE.\n"
            "• **Sans clé d'exécution** : Crée l'EXE sans clé d'exécution.\n"
            "• **Désactiver Tcl** : Désactive le support Tcl/Tk (par ex. si non nécessaire).\n\n"
            "📝 **Options supplémentaires :**\n"
            "Saisissez ici directement des paramètres PyInstaller supplémentaires.\n"
            "Exemple de saisie :\n"
            "--add-binary=\"C:/libs/extra.dll;extra.dll\" --hidden-import=asyncio\n\n"
            "✅ **Conseils pour des saisies réussies :**\n"
            "• **Ajout de données** : Utilisez des chemins absolus et assurez-vous que les fichiers/dossiers existent.\n"
            "• **Imports cachés** : Listez les modules sans espaces, séparés par des virgules.\n"
            "  Exemple :\n"
            "  numpy,requests,flask\n"
            "• **Icône, Version, Splash** : Les fichiers doivent exister et être correctement spécifiés.\n"
            "• **Dossier de sortie** : Doit exister ou pouvoir être créé automatiquement.\n"
            "• **Script** : Doit être un script Python valide.\n\n"
            "🖱️ **Boutons :**\n"
            "• **Enregistrer** : Enregistre les paramètres actuels du projet.\n"
            "• **Annuler** : Ferme la fenêtre de l'éditeur sans enregistrer.\n\n"
            "🔒 **Options PyArmor (Protection & Obfuscation)**\n"
            "• **--obf-code <0|1|2>** : Contrôle le niveau d'obfuscation du code (0=aucun, 1=normal, 2=élevé).\n"
            "• **--obf-module <0|1>** : Obfusque l'ensemble du module (1=activé).\n"
            "• **--mix-str** : Chiffre les chaînes dans le code.\n"
            "• **--no-wrap** : Désactive le mode d'enveloppement par défaut.\n"
            "• **--private** : Active le mode privé (limite les accès internes).\n"
            "• **--restrict** : Active le mode restrictif pour le paquet.\n"
            "• **--assert-import** : S'assure que les modules importés sont obfusqués.\n"
            "• **--assert-call** : S'assure que les fonctions appelées sont obfusquées.\n"
            "• **--platform NOM** : Spécifie la plateforme cible (par ex. windows.x86_64).\n"
            "• **--use-runtime CHEMIN** : Utilise un paquet d'exécution à partir du chemin spécifié.\n"
            "• **--outer** : Utilise une clé d'exécution externe pour plus de sécurité.\n"
            "• **--expired DATE** : Définit une date d'expiration (par ex. 2025-12-31).\n"
            "• **--period N** : Intervalle de vérification pour la clé d'exécution.\n"
            "• **--bind-device DEV** : Lie le script à des appareils spécifiques (par ex. adresse MAC).\n"
            "• **--pack <onefile|onedir|NOM.spec>** : Emballe le projet obfusqué.\n"
            "• **-r, --recursive** : Chiffre récursivement les fichiers dans les sous-dossiers.\n"
            "• **-O CHEMIN** : Spécifie le dossier de sortie.\n"
            "• **--exclude MOTIF** : Exclut les fichiers ou chemins de l'obfuscation.\n\n"
            "Ces options peuvent être spécifiées directement dans les **Options PyArmor** dans l'éditeur.\n\n"
            "💡 **Exemple de saisie :**\n"
            " --platform windows.x86_64 --pack onefile --expired 2025-12-31 --bind-device 08:00:27:12:34:56\n"
            "🖱️ **Boutons :**\n"
            "• **Enregistrer** : Enregistre les paramètres actuels du projet.\n"
            "• **Annuler** : Ferme la fenêtre de l'éditeur sans enregistrer.\n"
        ),
        "es": (
            "=== Ayuda – Descripción de funciones con ejemplos ===\n\n"
            "🚀 **Opciones generales**\n"
            "• **Onefile**\n"
            "  Empaqueta todo en un solo archivo ejecutable EXE (conveniente para una distribución sencilla).\n"
            "• **Consola**\n"
            "  Mantiene visible la ventana de consola durante la ejecución (útil para salidas de depuración).\n"
            "• **Modo Ventana**\n"
            "  Inicia la aplicación sin una ventana de consola visible (por ejemplo, para interfaces gráficas).\n"
            "• **Usar PyArmor**\n"
            "  Activa la ofuscación de código para protección adicional (opcional).\n\n"
            "📦 **Campos:**\n"
            "• **Nombre**\n"
            "  Nombre del proyecto o del archivo ejecutable.\n"
            "  Ejemplo de entrada:\n"
            "  MiHerramientaDeCopia\n\n"
            "• **Script**\n"
            "  Ruta al script de Python que se va a compilar.\n"
            "  Ejemplo de entrada:\n"
            "  C:/Proyectos/backupTool/backupWizard.py\n\n"
            "• **Carpeta de salida**\n"
            "  Carpeta de destino para el archivo EXE creado.\n"
            "  Ejemplo de entrada:\n"
            "  C:/Proyectos/backupTool/dist\n\n"
            "• **Ruta del icono**\n"
            "  Ruta a un archivo .ico para el ícono del programa.\n"
            "  Ejemplo de entrada:\n"
            "  C:/Proyectos/backupTool/assets/appicon.ico\n\n"
            "• **Añadir datos**\n"
            "  Archivos o carpetas adicionales para incluir en el EXE.\n"
            "  Formato: RutaOrigen:RutaDestino (separar múltiples entradas con punto y coma).\n"
            "  Ejemplo de entrada:\n"
            "  C:/Datos/config.ini:config;C:/Datos/imagenes:assets/imagenes\n\n"
            "• **Imports ocultos**\n"
            "  Módulos de Python que PyInstaller podría no detectar automáticamente.\n"
            "  Ejemplo de entrada:\n"
            "  requests,lxml,modulo_personalizado\n\n"
            "• **Archivo de versión**\n"
            "  Ruta a un archivo con información de versión.\n"
            "  Ejemplo de entrada:\n"
            "  C:/Proyectos/backupTool/version.txt\n\n"
            "• **Hook de ejecución**\n"
            "  Ruta a un script de Python ejecutado al iniciar la aplicación.\n"
            "  Ejemplo de entrada:\n"
            "  C:/Proyectos/backupTool/startup_hook.py\n\n"
            "• **Imagen de inicio**\n"
            "  Ruta a una imagen que se muestra al iniciar.\n"
            "  Ejemplo de entrada:\n"
            "  C:/Proyectos/backupTool/splashscreen.png\n\n"
            "• **Archivo Spec**\n"
            "  Ruta a un archivo .spec para configuraciones de compilación personalizadas de PyInstaller.\n"
            "  Ejemplo de entrada:\n"
            "  C:/Proyectos/backupTool/backupWizard.spec\n\n"
            "⚙️ **Opciones avanzadas:**\n"
            "• **UPX**: Activa la compresión del EXE (reduce el tamaño del archivo).\n"
            "• **Depuración**: Activa el modo de depuración (útil para solucionar errores).\n"
            "• **Limpiar**: Elimina archivos de compilación antiguos antes de crear nuevos.\n"
            "• **Strip**: Elimina símbolos de depuración, reduciendo el tamaño del EXE.\n"
            "• **Sin clave de ejecución**: Crea el EXE sin clave de ejecución.\n"
            "• **Desactivar Tcl**: Desactiva el soporte de Tcl/Tk (por ejemplo, si no es necesario).\n\n"
            "📝 **Opciones adicionales:**\n"
            "Ingresa parámetros adicionales de PyInstaller directamente aquí.\n"
            "Ejemplo de entrada:\n"
            "--add-binary=\"C:/libs/extra.dll;extra.dll\" --hidden-import=asyncio\n\n"
            "✅ **Consejos para entradas exitosas:**\n"
            "• **Añadir datos**: Usa rutas absolutas y asegúrate de que los archivos/carpetas existan.\n"
            "• **Imports ocultos**: Lista los módulos sin espacios, separados por comas.\n"
            "  Ejemplo:\n"
            "  numpy,requests,flask\n"
            "• **Icono, Versión, Splash**: Los archivos deben existir y estar correctamente especificados.\n"
            "• **Carpeta de salida**: Debe existir o poder crearse automáticamente.\n"
            "• **Script**: Debe ser un script de Python válido.\n\n"
            "🖱️ **Botones:**\n"
            "• **Guardar**: Guarda la configuración actual del proyecto.\n"
            "• **Cancelar**: Cierra la ventana del editor sin guardar.\n\n"
            "🔒 **Opciones de PyArmor (Protección y Ofuscación)**\n"
            "• **--obf-code <0|1|2>**: Controla el nivel de ofuscación del código (0=ninguno, 1=normal, 2=alto).\n"
            "• **--obf-module <0|1>**: Ofusca todo el módulo (1=activado).\n"
            "• **--mix-str**: Cifra las cadenas en el código.\n"
            "• **--no-wrap**: Desactiva el modo de envoltura predeterminado.\n"
            "• **--private**: Activa el modo privado (restringe accesos internos).\n"
            "• **--restrict**: Activa el modo restrictivo para el paquete.\n"
            "• **--assert-import**: Asegura que los módulos importados estén ofuscados.\n"
            "• **--assert-call**: Asegura que las funciones llamadas estén ofuscadas.\n"
            "• **--platform NOMBRE**: Especifica la plataforma objetivo (por ejemplo, windows.x86_64).\n"
            "• **--use-runtime RUTA**: Usa el paquete de tiempo de ejecución desde la ruta especificada.\n"
            "• **--outer**: Usa una clave de tiempo de ejecución externa para mayor seguridad.\n"
            "• **--expired FECHA**: Establece una fecha de caducidad (por ejemplo, 2025-12-31).\n"
            "• **--period N**: Intervalo de verificación para la clave de tiempo de ejecución.\n"
            "• **--bind-device DEV**: Vincula el script a dispositivos específicos (por ejemplo, dirección MAC).\n"
            "• **--pack <onefile|onedir|NOMBRE.spec>**: Empaqueta el proyecto ofuscado.\n"
            "• **-r, --recursive**: Cifra archivos en subdirectorios de forma recursiva.\n"
            "• **-O RUTA**: Especifica el directorio de salida.\n"
            "• **--exclude PATRÓN**: Excluye archivos o rutas de la ofuscación.\n\n"
            "Estas opciones se pueden especificar directamente en las **Opciones de PyArmor** en el editor.\n\n"
            "💡 **Ejemplo de entrada:**\n"
            " --platform windows.x86_64 --pack onefile --expired 2025-12-31 --bind-device 08:00:27:12:34:56\n"
            "🖱️ **Botones:**\n"
            "• **Guardar**: Guarda la configuración actual del proyecto.\n"
            "• **Cancelar**: Cierra la ventana del editor sin guardar.\n"
        ),
    },
    "main_helper": {
        "de": (
            "=== Hilfe – Hauptfenster ===\n\n"
            "Dieses Fenster dient zur Verwaltung und zum Kompilieren von Projekten.\n"
            "Hier eine Übersicht aller Funktionen:\n\n"
            "🟩 Hotkeys:\n Use Caps Lock for best use \n\n"
            "• Strg+C: Alle Projekte kompilieren.\n"
            "• Strg+A: Neues Projekt hinzufügen.\n"
            "• Strg+D: Ausgewähltes Projekt löschen.\n"
            "• Strg+Y: Kompiliermodus A/B/C umschalten.\n"
            "• Strg+L: Projektdatei (.apyscript) laden.\n"
            "• Strg+S: Projektdatei speichern.\n"
            "• Strg+Shift+S: Projektdatei speichern unter ...\n"
            "• Strg+E: Arbeitsverzeichnis leeren.\n"
            "• Strg+T: Design-Theme wechseln.\n"
            "• Strg+Q: Programm beenden.\n"
            "• Strg+F: Vollbild Modus.\n"
            "• Enter: Projekt bearbeiten.\n\n"
            "🟩 Skripte Bereich:\n"
            "• Hinzufügen (Shift+A): Ein neues Python- oder Spec-Projekt zur Liste hinzufügen.\n"
            "• Bearbeiten (Enter): Das ausgewählte Projekt bearbeiten (z.B. Pfade oder Optionen ändern).\n"
            "• Löschen: Entfernt das aktuell ausgewählte Projekt aus der Liste.\n\n"
            "🟩 Projekte Bereich:\n"
            "• Leeren: Löscht alle Projekte aus der Liste.\n"
            "• Laden: Lädt eine .apyscript-Datei und lädt die gespeicherten Projekte.\n"
            "• Speichern als: Speichert die aktuelle Projektliste als .apyscript oder .spec.\n\n"
            "🟩 Projektbereich:\n"
            "• Inspector: Öffnet den Debug-Inspector für die zuletzt erstellte Logdatei.\n"
            "• Alle kompilieren (Shift+C): Startet die Kompilierung aller ausgewählten Projekte.\n"
            "• Arbeitsverzeichnis leeren: Löscht alle compile_*.log-Dateien und den build-Ordner.\n\n"
            "🟩 Header:\n"
            "• Sprache auswählen: Wechselt die Sprache der Benutzeroberfläche.\n"
            "• INI laden: Lädt eine neue INI-Konfigurationsdatei.\n"
            "• About: Zeigt Informationen über dieses Programm.\n"
            "• 🎨 Colors: Ändert die Farben für Modus A/B.\n"
            "• 🖌️ Design: Wechselt das Design-Theme.\n\n"
            "🟩 Treeview:\n"
            "• Zeigt alle Projekte in der Liste an.\n"
            "• Checkboxen für Modus A/B zur Auswahl, welcher Modus verwendet wird.\n"
            "• Mit Doppelklick oder Enter das Projekt bearbeiten.\n\n"
        ),
        "en": (
            "=== Help – Main Window ===\n\n"
            "This window is used for managing and compiling projects.\n"
            "Here is an overview of all functions:\n\n"
            "🟩 Hotkeys:\n Use Caps Lock for best use \n\n"
            "• Ctrl+C: Compile all projects.\n"
            "• Ctrl+A: Add a new project.\n"
            "• Ctrl+D: Delete the selected project.\n"
            "• Ctrl+Y: Switch between compile modes A/B/C.\n"
            "• Ctrl+L: Load a project file (.apyscript).\n"
            "• Ctrl+S: Save the project file.\n"
            "• Ctrl+Shift+S: Save the project file as...\n"
            "• Ctrl+E: Clear the working directory.\n"
            "• Ctrl+T: Switch design theme.\n"
            "• Ctrl+Q: Exit the program.\n"
            "• Ctrl+F: Fullscreen mode.\n"
            "• Enter: Edit project.\n\n"
            "🟩 Scripts Section:\n"
            "• Add (Shift+A): Add a new Python or Spec project to the list.\n"
            "• Edit (Enter): Edit the selected project (e.g., change paths or options).\n"
            "• Delete: Remove the currently selected project from the list.\n\n"
            "🟩 Projects Section:\n"
            "• Clear: Deletes all projects from the list.\n"
            "• Load: Loads a .apyscript file and retrieves the saved projects.\n"
            "• Save As: Saves the current project list as .apyscript or .spec.\n\n"
            "🟩 Project Section:\n"
            "• Inspector: Opens the debug inspector for the latest created log file.\n"
            "• Compile All (Shift+C): Starts compiling all selected projects.\n"
            "• Clear Working Directory: Deletes all compile_*.log files and the build folder.\n\n"
            "🟩 Header:\n"
            "• Select Language: Switches the user interface language.\n"
            "• Load INI: Loads a new INI configuration file.\n"
            "• About: Displays information about this program.\n"
            "• 🎨 Colors: Changes the colors for Mode A/B.\n"
            "• 🖌️ Design: Switches the design theme.\n\n"
            "🟩 Treeview:\n"
            "• Displays all projects in the list.\n"
            "• Checkboxes for Mode A/B to select which mode is used.\n"
            "• Double-click or press Enter to edit the project.\n\n"
        ),
        "fr": (
            "=== Aide – Fenêtre principale ===\n\n"
            "Cette fenêtre sert à gérer et compiler les projets.\n"
            "Voici un aperçu de toutes les fonctions :\n\n"
            "🟩 Raccourcis clavier :\n Utilisez la touche Verr Maj pour une meilleure expérience \n\n"
            "• Ctrl+C : Compiler tous les projets.\n"
            "• Ctrl+A : Ajouter un nouveau projet.\n"
            "• Ctrl+D : Supprimer le projet sélectionné.\n"
            "• Ctrl+Y : Basculer entre les modes de compilation A/B/C.\n"
            "• Ctrl+L : Charger un fichier de projet (.apyscript).\n"
            "• Ctrl+S : Enregistrer le fichier de projet.\n"
            "• Ctrl+Shift+S : Enregistrer le fichier de projet sous...\n"
            "• Ctrl+E : Vider le répertoire de travail.\n"
            "• Ctrl+T : Changer le thème de design.\n"
            "• Ctrl+Q : Quitter le programme.\n"
            "• Ctrl+F : Mode plein écran.\n"
            "• Entrée : Modifier le projet.\n\n"
            "🟩 Section Scripts :\n"
            "• Ajouter (Shift+A) : Ajoute un nouveau projet Python ou Spec à la liste.\n"
            "• Modifier (Entrée) : Modifie le projet sélectionné (par ex. changer les chemins ou options).\n"
            "• Supprimer : Supprime le projet actuellement sélectionné de la liste.\n\n"
            "🟩 Section Projets :\n"
            "• Vider : Supprime tous les projets de la liste.\n"
            "• Charger : Charge un fichier .apyscript et récupère les projets enregistrés.\n"
            "• Enregistrer sous : Enregistre la liste de projets actuelle sous .apyscript ou .spec.\n\n"
            "🟩 Section Projet :\n"
            "• Inspecteur : Ouvre l'inspecteur de débogage pour le dernier fichier de log créé.\n"
            "• Compiler tout (Shift+C) : Lance la compilation de tous les projets sélectionnés.\n"
            "• Vider le répertoire de travail : Supprime tous les fichiers compile_*.log et le dossier build.\n\n"
            "🟩 En-tête :\n"
            "• Sélectionner la langue : Change la langue de l'interface utilisateur.\n"
            "• Charger INI : Charge un nouveau fichier de configuration INI.\n"
            "• À propos : Affiche des informations sur ce programme.\n"
            "• 🎨 Couleurs : Modifie les couleurs pour les modes A/B.\n"
            "• 🖌️ Design : Change le thème de design.\n\n"
            "🟩 Treeview :\n"
            "• Affiche tous les projets dans la liste.\n"
            "• Cases à cocher pour les modes A/B pour sélectionner le mode utilisé.\n"
            "• Double-clic ou touche Entrée pour modifier le projet.\n\n"
        ),
        "es": (
            "=== Ayuda – Ventana Principal ===\n\n"
            "Esta ventana se utiliza para gestionar y compilar proyectos.\n"
            "Aquí tienes una descripción general de todas las funciones:\n\n"
            "🟩 Atajos de teclado:\n Usa Bloq Mayús para un mejor uso \n\n"
            "• Ctrl+C: Compilar todos los proyectos.\n"
            "• Ctrl+A: Agregar un nuevo proyecto.\n"
            "• Ctrl+D: Eliminar el proyecto seleccionado.\n"
            "• Ctrl+Y: Cambiar entre modos de compilación A/B/C.\n"
            "• Ctrl+L: Cargar un archivo de proyecto (.apyscript).\n"
            "• Ctrl+S: Guardar el archivo de proyecto.\n"
            "• Ctrl+Shift+S: Guardar el archivo de proyecto como...\n"
            "• Ctrl+E: Limpiar el directorio de trabajo.\n"
            "• Ctrl+T: Cambiar el tema de diseño.\n"
            "• Ctrl+Q: Salir del programa.\n"
            "• Ctrl+F: Modo de pantalla completa.\n"
            "• Enter: Editar proyecto.\n\n"
            "🟩 Sección de Scripts:\n"
            "• Agregar (Shift+A): Añade un nuevo proyecto Python o Spec a la lista.\n"
            "• Editar (Enter): Edita el proyecto seleccionado (por ejemplo, cambiar rutas u opciones).\n"
            "• Eliminar: Elimina el proyecto actualmente seleccionado de la lista.\n\n"
            "🟩 Sección de Proyectos:\n"
            "• Limpiar: Elimina todos los proyectos de la lista.\n"
            "• Cargar: Carga un archivo .apyscript y recupera los proyectos guardados.\n"
            "• Guardar como: Guarda la lista de proyectos actual como .apyscript o .spec.\n\n"
            "🟩 Sección de Proyecto:\n"
            "• Inspector: Abre el inspector de depuración para el último archivo de registro creado.\n"
            "• Compilar todo (Shift+C): Inicia la compilación de todos los proyectos seleccionados.\n"
            "• Limpiar directorio de trabajo: Elimina todos los archivos compile_*.log y la carpeta build.\n\n"
            "🟩 Encabezado:\n"
            "• Seleccionar idioma: Cambia el idioma de la interfaz de usuario.\n"
            "• Cargar INI: Carga un nuevo archivo de configuración INI.\n"
            "• Acerca de: Muestra información sobre este programa.\n"
            "• 🎨 Colores: Cambia los colores para los modos A/B.\n"
            "• 🖌️ Diseño: Cambia el tema de diseño.\n\n"
            "🟩 Treeview:\n"
            "• Muestra todos los proyectos en la lista.\n"
            "• Casillas de verificación para los modos A/B para seleccionar qué modo se usa.\n"
            "• Doble clic o presionar Enter para editar el proyecto.\n\n"
        ),
        
    },
    "spec_helper": {
        "de": (
            "=== Hilfe – Spec-Editor Beschreibung mit Beispielen ===\n\n"
            "🚀 **Allgemeine Optionen**\n"
            "• **Onefile**\n"
            "  Bündelt die Anwendung in einer einzigen ausführbaren EXE-Datei (ideal für einfache Verteilung).\n"
            "• **Konsole**\n"
            "  Zeigt ein Konsolenfenster beim Ausführen der Anwendung an (nützlich für Debugging).\n"
            "• **Windowed**\n"
            "  Startet die Anwendung ohne ein sichtbares Konsolenfenster (z.B. für GUI-Anwendungen).\n\n"
            "📦 **Felder:**\n"
            "• **Name**\n"
            "  Der Name der ausführbaren Datei oder des Projekts.\n"
            "  Eingabebeispiel:\n"
            "  backupWizard\n\n"
            "• **Icon**\n"
            "  Pfad zu einer .ico-Datei, die als Symbol für die EXE verwendet wird.\n"
            "  Eingabebeispiel:\n"
            "  C:/xampp/htdocs/cebterOS/engineering/icon_services.ico\n\n"
            "• **Spec-Datei**\n"
            "  Pfad zu einer .spec-Datei, die PyInstaller-Build-Konfigurationen enthält.\n"
            "  Eingabebeispiel:\n"
            "  C:/xampp/htdocs/cebterOS/engineering/backupWizard.spec\n\n"
            "• **Runtime Hook**\n"
            "  Pfad zu einem Python-Skript, das beim Start der Anwendung ausgeführt wird.\n"
            "  Eingabebeispiel:\n"
            "  C:/Projekte/backupTool/startup_hook.py\n\n"
            "• **Hidden Imports**\n"
            "  Python-Module, die PyInstaller möglicherweise nicht automatisch erkennt.\n"
            "  Eingabebeispiel:\n"
            "  requests\nlxml\ncustom_module\n"
            "  (Ein Modul pro Zeile oder durch Kommas getrennt)\n\n"
            "• **Binaries (add_data)**\n"
            "  Zusätzliche Dateien oder Ordner, die in die EXE eingebunden werden sollen.\n"
            "  Format: Quellpfad:Zielpfad (mehrere Einträge in neuen Zeilen).\n"
            "  Eingabebeispiel:\n"
            "  C:/Daten/config.ini:config\nC:/Daten/bilder:assets/bilder\n\n"
            "⚙️ **Erweiterte Optionen:**\n"
            "• **UPX aktivieren**: Komprimiert die EXE-Datei mit UPX, um die Dateigröße zu reduzieren.\n"
            "• **Debug aktiv**: Aktiviert den Debug-Modus für detaillierte Ausgaben während des Build-Prozesses.\n"
            "• **Clean aktiv**: Löscht alte Build-Dateien vor einem neuen Build.\n"
            "• **Strip aktiv**: Entfernt Debug-Symbole aus der EXE, um die Dateigröße zu verringern.\n\n"
            "✅ **Tipps für erfolgreiche Eingaben:**\n"
            "• **Binaries (add_data)**: Verwende absolute Pfade und stelle sicher, dass die Dateien/Ordner existieren.\n"
            "• **Hidden Imports**: Gib Module ohne Leerzeichen an, entweder in neuen Zeilen oder durch Kommas getrennt.\n"
            "  Beispiel:\n"
            "  numpy\nrequests\nflask\n"
            "• **Icon und Spec-Datei**: Die Dateien müssen existieren und korrekt angegeben werden.\n"
            "• Überprüfe Pfade auf Tippfehler, insbesondere bei Groß-/Kleinschreibung.\n\n"
            "🖱️ **Schaltflächen:**\n"
            "• **Datei hinzufügen**: Fügt eine Daterosenkrantz-Dateien einbinden (z.B. Bilder, DLLs).\n"
            "• **Speichern**: Speichert die aktuellen Einstellungen des Spec-Editors.\n"
            "• **Abbrechen**: Schließt das Spec-Editor-Fenster ohne Speichern.\n"
            "• **Help**: Öffnet dieses Hilfefenster mit Anleitungen.\n"
        ),
        "en": (
            "=== Help – Spec Editor Description with Examples ===\n\n"
            "🚀 **General Options**\n"
            "• **Onefile**\n"
            "  Bundle the application into a single executable EXE file (ideal for easy distribution).\n"
            "• **Console**\n"
            "  Display a console window during application execution (useful for debugging).\n"
            "• **Windowed**\n"
            "  Launch the application without a visible console window (e.g., for GUI applications).\n\n"
            "📦 **Fields:**\n"
            "• **Name**\n"
            "  The name of the executable file or project.\n"
            "  Example input:\n"
            "  backupWizard\n\n"
            "• **Icon**\n"
            "  Path to an .ico file used as the icon for the EXE.\n"
            "  Example input:\n"
            "  C:/xampp/htdocs/cebterOS/engineering/icon_services.ico\n\n"
            "• **Spec File**\n"
            "  Path to a .spec file containing PyInstaller build configurations.\n"
            "  Example input:\n"
            "  C:/xampp/htdocs/cebterOS/engineering/backupWizard.spec\n\n"
            "• **Runtime Hook**\n"
            "  Path to a Python script executed at application startup.\n"
            "  Example input:\n"
            "  C:/Projects/backupTool/startup_hook.py\n\n"
            "• **Hidden Imports**\n"
            "  Python modules that PyInstaller might not automatically detect.\n"
            "  Example input:\n"
            "  requests\nlxml\ncustom_module\n"
            "  (One module per line or comma-separated)\n\n"
            "• **Binaries (add_data)**\n"
            "  Additional files or folders to be included in the EXE.\n"
            "  Format: SourcePath:TargetPath (multiple entries on new lines).\n"
            "  Example input:\n"
            "  C:/Data/config.ini:config\nC:/Data/images:assets/images\n\n"
            "⚙️ **Advanced Options:**\n"
            "• **Enable UPX**: Compresses the EXE file with UPX to reduce file size.\n"
            "• **Enable Debug**: Activates debug mode for detailed outputs during the build process.\n"
            "• **Enable Clean**: Deletes old build files before a new build.\n"
            "• **Enable Strip**: Removes debug symbols from the EXE to reduce file size.\n\n"
            "✅ **Tips for Successful Inputs:**\n"
            "• **Binaries (add_data)**: Use absolute paths and ensure files/folders exist.\n"
            "• **Hidden Imports**: Specify modules without spaces, either on new lines or comma-separated.\n"
            "  Example:\n"
            "  numpy\nrequests\nflask\n"
            "• **Icon and Spec File**: Files must exist and be correctly specified.\n"
            "• Check paths for typos, especially case sensitivity.\n\n"
            "🖱️ **Buttons:**\n"
            "• **Add File**: Adds files to include (e.g., images, DLLs).\n"
            "• **Save**: Saves the current settings of the Spec Editor.\n"
            "• **Cancel**: Closes the Spec Editor window without saving.\n"
            "• **Help**: Opens this help window with instructions.\n"
        ),
        "fr": (
            "=== Aide – Description de l'éditeur Spec avec exemples ===\n\n"
            "🚀 **Options générales**\n"
            "• **Onefile**\n"
            "  Regroupe l'application dans un seul fichier exécutable EXE (idéal pour une distribution simple).\n"
            "• **Console**\n"
            "  Affiche une fenêtre de console lors de l'exécution de l'application (utile pour le débogage).\n"
            "• **Fenêtré**\n"
            "  Lance l'application sans fenêtre de console visible (par ex. pour les applications GUI).\n\n"
            "📦 **Champs :**\n"
            "• **Nom**\n"
            "  Nom du fichier exécutable ou du projet.\n"
            "  Exemple de saisie :\n"
            "  backupWizard\n\n"
            "• **Icône**\n"
            "  Chemin vers un fichier .ico utilisé comme icône pour l'EXE.\n"
            "  Exemple de saisie :\n"
            "  C:/xampp/htdocs/cebterOS/engineering/icon_services.ico\n\n"
            "• **Fichier Spec**\n"
            "  Chemin vers un fichier .spec contenant les configurations de build PyInstaller.\n"
            "  Exemple de saisie :\n"
            "  C:/xampp/htdocs/cebterOS/engineering/backupWizard.spec\n\n"
            "• **Hook d'exécution**\n"
            "  Chemin vers un script Python exécuté au démarrage de l'application.\n"
            "  Exemple de saisie :\n"
            "  C:/Projets/backupTool/startup_hook.py\n\n"
            "• **Imports cachés**\n"
            "  Modules Python que PyInstaller pourrait ne pas détecter automatiquement.\n"
            "  Exemple de saisie :\n"
            "  requests\nlxml\nmon_module_personnalise\n"
            "  (Un module par ligne ou séparé par des virgules)\n\n"
            "• **Binaires (add_data)**\n"
            "  Fichiers ou dossiers supplémentaires à inclure dans l'EXE.\n"
            "  Format : CheminSource:CheminCible (entrées multiples sur de nouvelles lignes).\n"
            "  Exemple de saisie :\n"
            "  C:/Donnees/config.ini:config\nC:/Donnees/images:assets/images\n\n"
            "⚙️ **Options avancées :**\n"
            "• **Activer UPX** : Compresse le fichier EXE avec UPX pour réduire la taille du fichier.\n"
            "• **Activer Débogage** : Active le mode débogage pour des sorties détaillées pendant le processus de build.\n"
            "• **Activer Nettoyage** : Supprime les anciens fichiers de build avant un nouveau build.\n"
            "• **Activer Strip** : Supprime les symboles de débogage de l'EXE pour réduire la taille du fichier.\n\n"
            "✅ **Conseils pour des saisies réussies :**\n"
            "• **Binaires (add_data)** : Utilisez des chemins absolus et assurez-vous que les fichiers/dossiers existent.\n"
            "• **Imports cachés** : Spécifiez les modules sans espaces, soit sur de nouvelles lignes, soit séparés par des virgules.\n"
            "  Exemple :\n"
            "  numpy\nrequests\nflask\n"
            "• **Icône et Fichier Spec** : Les fichiers doivent exister et être correctement spécifiés.\n"
            "• Vérifiez les chemins pour éviter les erreurs, notamment la casse.\n\n"
            "🖱️ **Boutons :**\n"
            "• **Ajouter un fichier** : Ajoute des fichiers à inclure (par ex. images, DLLs).\n"
            "• **Enregistrer** : Enregistre les paramètres actuels de l'éditeur Spec.\n"
            "• **Annuler** : Ferme la fenêtre de l'éditeur Spec sans enregistrer.\n"
            "• **Aide** : Ouvre cette fenêtre d'aide avec des instructions.\n"
        ),
        "es": (
            "=== Ayuda – Descripción del Editor Spec con Ejemplos ===\n\n"
            "🚀 **Opciones generales**\n"
            "• **Onefile**\n"
            "  Empaqueta la aplicación en un solo archivo ejecutable EXE (ideal para una distribución sencilla).\n"
            "• **Consola**\n"
            "  Muestra una ventana de consola durante la ejecución de la aplicación (útil para depuración).\n"
            "• **Ventana**\n"
            "  Inicia la aplicación sin una ventana de consola visible (por ejemplo, para aplicaciones GUI).\n\n"
            "📦 **Campos:**\n"
            "• **Nombre**\n"
            "  Nombre del archivo ejecutable o del proyecto.\n"
            "  Ejemplo de entrada:\n"
            "  backupWizard\n\n"
            "• **Icono**\n"
            "  Ruta a un archivo .ico utilizado como ícono para el EXE.\n"
            "  Ejemplo de entrada:\n"
            "  C:/xampp/htdocs/cebterOS/engineering/icon_services.ico\n\n"
            "• **Archivo Spec**\n"
            "  Ruta a un archivo .spec que contiene configuraciones de compilación de PyInstaller.\n"
            "  Ejemplo de entrada:\n"
            "  C:/xampp/htdocs/cebterOS/engineering/backupWizard.spec\n\n"
            "• **Hook de ejecución**\n"
            "  Ruta a un script de Python ejecutado al iniciar la aplicación.\n"
            "  Ejemplo de entrada:\n"
            "  C:/Proyectos/backupTool/startup_hook.py\n\n"
            "• **Imports ocultos**\n"
            "  Módulos de Python que PyInstaller podría no detectar automáticamente.\n"
            "  Ejemplo de entrada:\n"
            "  requests\nlxml\nmodulo_personalizado\n"
            "  (Un módulo por línea o separados por comas)\n\n"
            "• **Binarios (add_data)**\n"
            "  Archivos o carpetas adicionales para incluir en el EXE.\n"
            "  Formato: RutaOrigen:RutaDestino (entradas múltiples en líneas nuevas).\n"
            "  Ejemplo de entrada:\n"
            "  C:/Datos/config.ini:config\nC:/Datos/imagenes:assets/imagenes\n\n"
            "⚙️ **Opciones avanzadas:**\n"
            "• **Activar UPX**: Comprime el archivo EXE con UPX para reducir el tamaño del archivo.\n"
            "• **Activar Depuración**: Activa el modo de depuración para salidas detalladas durante el proceso de compilación.\n"
            "• **Activar Limpieza**: Elimina archivos de compilación antiguos antes de un nuevo proceso de compilación.\n"
            "• **Activar Strip**: Elimina los símbolos de depuración del EXE para reducir el tamaño del archivo.\n\n"
            "✅ **Consejos para entradas exitosas:**\n"
            "• **Binarios (add_data)**: Usa rutas absolutas y asegúrate de que los archivos/carpetas existan.\n"
            "• **Imports ocultos**: Especifica los módulos sin espacios, ya sea en líneas nuevas o separados por comas.\n"
            "  Ejemplo:\n"
            "  numpy\nrequests\nflask\n"
            "• **Icono y Archivo Spec**: Los archivos deben existir y estar correctamente especificados.\n"
            "• Verifica las rutas para evitar errores, especialmente en la sensibilidad a mayúsculas y minúsculas.\n\n"
            "🖱️ **Botones:**\n"
            "• **Agregar archivo**: Añade archivos para incluir (por ejemplo, imágenes, DLLs).\n"
            "• **Guardar**: Guarda la configuración actual del Editor Spec.\n"
            "• **Cancelar**: Cierra la ventana del Editor Spec sin guardar.\n"
            "• **Ayuda**: Abre esta ventana de ayuda con instrucciones.\n"
        ),        
    },
    "nuitka_helper": {
        "de": (
            "=== Hilfe – Nuitka Compilation Editor ===\n\n"
            "🚀 **Allgemeine Optionen**\n"
            "• **Use Nuitka**\n"
            "  Aktiviert die Kompilierung mit Nuitka, um Python-Skripte in ausführbare Programme umzuwandeln. Deaktiviert bleibt das Skript ein normales Python-Programm, das Python benötigt.\n"
            "• **Standalone**\n"
            "  Erstellt eine eigenständige Anwendung mit allen Abhängigkeiten (z. B. Module, Bibliotheken) in einem Ordner. Ideal für die Verteilung auf Systeme ohne Python. Erzeugt größere Dateien (oft 100 MB+).\n"
            "• **Onefile**\n"
            "  Packt die gesamte Anwendung in eine einzige .exe-Datei (Windows) oder ein Programm (Linux/macOS). Beim Start wird die Datei temporär entpackt, was die Startzeit verlängern kann.\n"
            "• **Console**\n"
            "  Öffnet ein Konsolenfenster beim Programmstart, das Ausgaben (z. B. print oder Fehlermeldungen) anzeigt. Nützlich für Debugging, für Endnutzer oft deaktivieren.\n\n"
            "📦 **Weitere Optionen**\n"
            "• **Follow Imports**\n"
            "  Erkennt und bindet alle importierten Module automatisch ein (z. B. numpy, requests). Spart manuelle Konfiguration, kann aber die Dateigröße erhöhen. Deaktivieren, wenn du Module gezielt einbinden willst.\n"
            "• **Follow Stdlib**\n"
            "  Bindet Python-Standardbibliotheken (z. B. os, sys) ein, falls nicht automatisch erkannt. Selten nötig, nur bei obskuren Modulen wie ctypes aktivieren.\n"
            "• **Plugins**\n"
            "  Aktiviert Unterstützung für spezielle Bibliotheken (z. B. --plugin-enable=pyqt6 für PyQt6). Ohne passende Plugins können GUI- oder Datenbibliotheken fehlerhaft kompiliert werden.\n"
            "• **Extra Options**\n"
            "  Freitextfeld für zusätzliche Nuitka-Parameter, z. B. --include-module=mein_modul oder --noinclude-pandas. Falsche Eingaben führen zu Fehlern, siehe Nuitka-Dokumentation.\n"
            "• **Output Dir**\n"
            "  Der Ordner, in den die kompilierten Dateien geschrieben werden. Muss existieren und beschreibbar sein, z. B. C:\\MeinProjekt\\output.\n\n"
            "⚙️ **Leistungsoptionen**\n"
            "• **LTO (Link Time Optimization)**\n"
            "  Optimiert die Binärdatei für kleinere Größe und schnellere Ausführung. Optionen:\n"
            "  - **auto**: Nuitka wählt basierend auf Projektgröße (Standard).\n"
            "  - **yes**: Maximale Optimierung, aber längere Kompilierungszeit und höherer RAM-Verbrauch (8 GB+).\n"
            "  - **no**: Schnellere Kompilierung, größere Datei. Bei Fehlern no testen.\n"
            "• **Jobs**\n"
            "  Anzahl paralleler Kompilierungsprozesse (1, 2, 4, 8). Mehr Jobs beschleunigen, verbrauchen aber mehr RAM. Für moderne PCs: 4 oder 8, bei wenig RAM: 1 oder 2.\n"
            "• **Show Progress / Memory / Scons**\n"
            "  Zeigt Details während der Kompilierung:\n"
            "  - **Progress**: Fortschritt (z. B. 'Modul X wird kompiliert').\n"
            "  - **Memory**: Speicherverbrauch, hilfreich bei LTO.\n"
            "  - **Scons**: Details des Build-Systems, für fortgeschrittene Nutzer.\n"
            "• **Windows UAC Admin**\n"
            "  Fordert Admin-Rechte beim Programmstart (UAC-Abfrage). Nur aktivieren, wenn die Anwendung Systemzugriffe benötigt (z. B. Schreiben in C:\\Program Files).\n\n"
            "🎨 **Windows-spezifische Optionen**\n"
            "• **Windows Icon**\n"
            "  Pfad zu einer .ico-Datei (z. B. C:\\icon.ico) für das Programmsymbol in Taskleiste/Explorer. Muss mehrere Auflösungen (16x16, 32x32) enthalten.\n"
            "• **Windows Splash**\n"
            "  Pfad zu einem Bild (z. B. C:\\splash.png), das beim Programmstart angezeigt wird. Nützlich bei langer Ladezeit, niedrige Auflösung bevorzugen.\n\n"
            "✅ **Tipps**\n"
            "• Überprüfe Script-Pfad und Output-Ordner vor der Kompilierung.\n"
            "• Nutze nur Plugins, die mit deinen Bibliotheken kompatibel sind (siehe Nuitka-Dokumentation).\n"
            "• Security Level Buttons wählen vordefinierte Einstellungen (z. B. schnell oder sicher). Mit Analyse prüfen.\n"
            "• Aktiviere Show Progress/Memory bei Fehlern, um Probleme zu finden.\n\n"
            "🖱️ **Schaltflächen**\n"
            "• **Analyse**: Prüft Pfade, Plugins und Einstellungen auf Fehler vor der Kompilierung.\n"
            "• **Save**: Speichert die Einstellungen und schließt den Editor.\n"
            "• **Cancel**: Schließt ohne Speichern.\n"
            "• **Help**: Öffnet dieses Hilfefenster.\n"
        ),
        "en": (
            "=== Help – Nuitka Compilation Editor ===\n\n"
            "🚀 **General Options**\n"
            "• **Use Nuitka**\n"
            "  Enables compilation with Nuitka to convert Python scripts into executable programs. If disabled, the script remains a regular Python program requiring Python.\n"
            "• **Standalone**\n"
            "  Creates a standalone application with all dependencies (e.g., modules, libraries) in one folder. Ideal for distribution on systems without Python. Generates larger files (often 100 MB+).\n"
            "• **Onefile**\n"
            "  Packs the entire application into a single .exe file (Windows) or program (Linux/macOS). Temporarily unpacked at runtime, which may increase startup time.\n"
            "• **Console**\n"
            "  Opens a console window at program start, showing outputs (e.g., print or error messages). Useful for debugging; often disabled for end users.\n\n"
            "📦 **Additional Options**\n"
            "• **Follow Imports**\n"
            "  Automatically detects and includes all imported modules (e.g., numpy, requests). Saves manual configuration but may increase file size. Disable to include modules selectively.\n"
            "• **Follow Stdlib**\n"
            "  Includes Python standard libraries (e.g., os, sys) if not automatically detected. Rarely needed, only enable for obscure modules like ctypes.\n"
            "• **Plugins**\n"
            "  Enables support for specific libraries (e.g., --plugin-enable=pyqt6 for PyQt6). Without appropriate plugins, GUI or data libraries may compile incorrectly.\n"
            "• **Extra Options**\n"
            "  Free text field for additional Nuitka parameters, e.g., --include-module=my_module or --noinclude-pandas. Incorrect inputs cause errors; see Nuitka documentation.\n"
            "• **Output Dir**\n"
            "  The folder where compiled files are written. Must exist and be writable, e.g., C:\\MyProject\\output.\n\n"
            "⚙️ **Performance Options**\n"
            "• **LTO (Link Time Optimization)**\n"
            "  Optimizes the binary for smaller size and faster execution. Options:\n"
            "  - **auto**: Nuitka chooses based on project size (default).\n"
            "  - **yes**: Maximum optimization, but longer compilation time and higher RAM usage (8 GB+).\n"
            "  - **no**: Faster compilation, larger file. Test with no if errors occur.\n"
            "• **Jobs**\n"
            "  Number of parallel compilation processes (1, 2, 4, 8). More jobs speed up compilation but use more RAM. For modern PCs: 4 or 8; for low RAM: 1 or 2.\n"
            "• **Show Progress / Memory / Scons**\n"
            "  Shows details during compilation:\n"
            "  - **Progress**: Progress (e.g., 'Module X is being compiled').\n"
            "  - **Memory**: Memory usage, helpful for LTO.\n"
            "  - **Scons**: Build system details, for advanced users.\n"
            "• **Windows UAC Admin**\n"
            "  Requests admin rights at program start (UAC prompt). Enable only if the application requires system access (e.g., writing to C:\\Program Files).\n\n"
            "🎨 **Windows-specific Options**\n"
            "• **Windows Icon**\n"
            "  Path to an .ico file (e.g., C:\\icon.ico) for the program icon in the taskbar/explorer. Must include multiple resolutions (16x16, 32x32).\n"
            "• **Windows Splash**\n"
            "  Path to an image (e.g., C:\\splash.png) displayed at program start. Useful for long load times; prefer low resolution.\n\n"
            "✅ **Tips**\n"
            "• Check script path and output folder before compilation.\n"
            "• Use only plugins compatible with your libraries (see Nuitka documentation).\n"
            "• Security Level Buttons select predefined settings (e.g., fast or secure). Verify with analysis.\n"
            "• Enable Show Progress/Memory for troubleshooting errors.\n\n"
            "🖱️ **Buttons**\n"
            "• **Analyze**: Checks paths, plugins, and settings for errors before compilation.\n"
            "• **Save**: Saves settings and closes the editor.\n"
            "• **Cancel**: Closes without saving.\n"
            "• **Help**: Opens this help window.\n"
        ),
        "fr": (
            "=== Aide – Éditeur de compilation Nuitka ===\n\n"
            "🚀 **Options générales**\n"
            "• **Utiliser Nuitka**\n"
            "  Active la compilation avec Nuitka pour convertir les scripts Python en programmes exécutables. Si désactivé, le script reste un programme Python standard nécessitant Python.\n"
            "• **Standalone**\n"
            "  Crée une application autonome avec toutes les dépendances (modules, bibliothèques) dans un seul dossier. Idéal pour la distribution sur des systèmes sans Python. Génère des fichiers plus volumineux (souvent 100 Mo+).\n"
            "• **Onefile**\n"
            "  Regroupe toute l'application dans un seul fichier .exe (Windows) ou programme (Linux/macOS). Décompressé temporairement au démarrage, ce qui peut augmenter le temps de lancement.\n"
            "• **Console**\n"
            "  Ouvre une fenêtre de console au démarrage du programme, affichant les sorties (par ex. print ou messages d'erreur). Utile pour le débogage ; souvent désactivé pour les utilisateurs finaux.\n\n"
            "📦 **Options supplémentaires**\n"
            "• **Suivre les imports**\n"
            "  Détecte et inclut automatiquement tous les modules importés (par ex. numpy, requests). Évite une configuration manuelle mais peut augmenter la taille du fichier. Désactivez pour inclure les modules de manière sélective.\n"
            "• **Suivre la bibliothèque standard**\n"
            "  Inclut les bibliothèques standard Python (par ex. os, sys) si elles ne sont pas détectées automatiquement. Rarement nécessaire, activez uniquement pour des modules rares comme ctypes.\n"
            "• **Plugins**\n"
            "  Active le support pour des bibliothèques spécifiques (par ex. --plugin-enable=pyqt6 pour PyQt6). Sans plugins appropriés, les bibliothèques GUI ou de données peuvent être compilées incorrectement.\n"
            "• **Options supplémentaires**\n"
            "  Champ de texte libre pour des paramètres Nuitka supplémentaires, par ex. --include-module=mon_module ou --noinclude-pandas. Des entrées incorrectes provoquent des erreurs ; voir la documentation Nuitka.\n"
            "• **Dossier de sortie**\n"
            "  Dossier où les fichiers compilés sont écrits. Doit exister et être accessible en écriture, par ex. C:\\MonProjet\\output.\n\n"
            "⚙️ **Options de performance**\n"
            "• **LTO (Optimisation au moment de la liaison)**\n"
            "  Optimise le binaire pour une taille réduite et une exécution plus rapide. Options :\n"
            "  - **auto** : Nuitka choisit en fonction de la taille du projet (par défaut).\n"
            "  - **yes** : Optimisation maximale, mais temps de compilation plus long et consommation de RAM élevée (8 Go+).\n"
            "  - **no** : Compilation plus rapide, fichier plus volumineux. Tester avec no en cas d'erreurs.\n"
            "• **Jobs**\n"
            "  Nombre de processus de compilation parallèles (1, 2, 4, 8). Plus de jobs accélèrent la compilation mais consomment plus de RAM. Pour les PC modernes : 4 ou 8 ; pour peu de RAM : 1 ou 2.\n"
            "• **Afficher la progression / Mémoire / Scons**\n"
            "  Affiche des détails pendant la compilation :\n"
            "  - **Progression** : Avancement (par ex. 'Module X en cours de compilation').\n"
            "  - **Mémoire** : Consommation de mémoire, utile pour LTO.\n"
            "  - **Scons** : Détails du système de build, pour les utilisateurs avancés.\n"
            "• **Windows UAC Admin**\n"
            "  Demande des droits d'administrateur au démarrage du programme (invite UAC). Activer uniquement si l'application nécessite un accès système (par ex. écriture dans C:\\Program Files).\n\n"
            "🎨 **Options spécifiques à Windows**\n"
            "• **Icône Windows**\n"
            "  Chemin vers un fichier .ico (par ex. C:\\icon.ico) pour l'icône du programme dans la barre des tâches/explorateur. Doit inclure plusieurs résolutions (16x16, 32x32).\n"
            "• **Splash Windows**\n"
            "  Chemin vers une image (par ex. C:\\splash.png) affichée au démarrage du programme. Utile pour les longs temps de chargement ; préférez une faible résolution.\n\n"
            "✅ **Conseils**\n"
            "• Vérifiez le chemin du script et le dossier de sortie avant la compilation.\n"
            "• Utilisez uniquement des plugins compatibles avec vos bibliothèques (voir la documentation Nuitka).\n"
            "• Les boutons de niveau de sécurité sélectionnent des paramètres prédéfinis (par ex. rapide ou sécurisé). Vérifiez avec l'analyse.\n"
            "• Activez Afficher la progression/Mémoire pour résoudre les erreurs.\n\n"
            "🖱️ **Boutons**\n"
            "• **Analyser** : Vérifie les chemins, plugins et paramètres pour détecter les erreurs avant la compilation.\n"
            "• **Enregistrer** : Enregistre les paramètres et ferme l'éditeur.\n"
            "• **Annuler** : Ferme sans enregistrer.\n"
            "• **Aide** : Ouvre cette fenêtre d'aide.\n"
        ),
        "es": (
            "=== Ayuda – Editor de Compilación Nuitka ===\n\n"
            "🚀 **Opciones generales**\n"
            "• **Usar Nuitka**\n"
            "  Activa la compilación con Nuitka para convertir scripts de Python en programas ejecutables. Si está desactivado, el script sigue siendo un programa Python normal que requiere Python.\n"
            "• **Independiente**\n"
            "  Crea una aplicación independiente con todas las dependencias (por ejemplo, módulos, bibliotecas) en una sola carpeta. Ideal para distribuir en sistemas sin Python. Genera archivos más grandes (a menudo 100 MB+).\n"
            "• **Onefile**\n"
            "  Empaqueta toda la aplicación en un solo archivo .exe (Windows) o programa (Linux/macOS). Se descomprime temporalmente en tiempo de ejecución, lo que puede aumentar el tiempo de inicio.\n"
            "• **Consola**\n"
            "  Abre una ventana de consola al iniciar el programa, mostrando salidas (por ejemplo, print o mensajes de error). Útil para depuración; a menudo desactivado para usuarios finales.\n\n"
            "📦 **Opciones adicionales**\n"
            "• **Seguir importaciones**\n"
            "  Detecta e incluye automáticamente todos los módulos importados (por ejemplo, numpy, requests). Ahorra configuración manual pero puede aumentar el tamaño del archivo. Desactiva para incluir módulos selectivamente.\n"
            "• **Seguir biblioteca estándar**\n"
            "  Incluye bibliotecas estándar de Python (por ejemplo, os, sys) si no se detectan automáticamente. Raramente necesario, activar solo para módulos poco comunes como ctypes.\n"
            "• **Plugins**\n"
            "  Habilita soporte para bibliotecas específicas (por ejemplo, --plugin-enable=pyqt6 para PyQt6). Sin los plugins adecuados, las bibliotecas de interfaz gráfica o de datos pueden compilarse incorrectamente.\n"
            "• **Opciones extra**\n"
            "  Campo de texto libre para parámetros adicionales de Nuitka, por ejemplo, --include-module=mi_modulo o --noinclude-pandas. Entradas incorrectas causan errores; consulta la documentación de Nuitka.\n"
            "• **Directorio de salida**\n"
            "  Carpeta donde se escriben los archivos compilados. Debe existir y ser escribible, por ejemplo, C:\\MiProyecto\\output.\n\n"
            "⚙️ **Opciones de rendimiento**\n"
            "• **LTO (Optimización en tiempo de enlace)**\n"
            "  Optimiza el binario para un tamaño menor y una ejecución más rápida. Opciones:\n"
            "  - **auto**: Nuitka elige según el tamaño del proyecto (predeterminado).\n"
            "  - **yes**: Optimización máxima, pero mayor tiempo de compilación y consumo de RAM (8 GB+).\n"
            "  - **no**: Compilación más rápida, archivo más grande. Prueba con no si hay errores.\n"
            "• **Jobs**\n"
            "  Número de procesos de compilación paralelos (1, 2, 4, 8). Más jobs aceleran la compilación pero usan más RAM. Para PCs modernos: 4 u 8; para poca RAM: 1 o 2.\n"
            "• **Mostrar progreso / Memoria / Scons**\n"
            "  Muestra detalles durante la compilación:\n"
            "  - **Progreso**: Avance (por ejemplo, 'Módulo X está siendo compilado').\n"
            "  - **Memoria**: Consumo de memoria, útil para LTO.\n"
            "  - **Scons**: Detalles del sistema de compilación, para usuarios avanzados.\n"
            "• **Windows UAC Admin**\n"
            "  Solicita derechos de administrador al iniciar el programa (aviso UAC). Activar solo si la aplicación requiere acceso al sistema (por ejemplo, escribir en C:\\Program Files).\n\n"
            "🎨 **Opciones específicas de Windows**\n"
            "• **Ícono de Windows**\n"
            "  Ruta a un archivo .ico (por ejemplo, C:\\icon.ico) para el ícono del programa en la barra de tareas/explorador. Debe incluir múltiples resoluciones (16x16, 32x32).\n"
            "• **Splash de Windows**\n"
            "  Ruta a una imagen (por ejemplo, C:\\splash.png) mostrada al iniciar el programa. Útil para tiempos de carga largos; prefiere baja resolución.\n\n"
            "✅ **Consejos**\n"
            "• Verifica la ruta del script y la carpeta de salida antes de la compilación.\n"
            "• Usa solo plugins compatibles con tus bibliotecas (consulta la documentación de Nuitka).\n"
            "• Los botones de nivel de seguridad seleccionan configuraciones predefinidas (por ejemplo, rápido o seguro). Verifica con análisis.\n"
            "• Activa Mostrar progreso/Memoria para solucionar errores.\n\n"
            "🖱️ **Botones**\n"
            "• **Analizar**: Verifica rutas, plugins y configuraciones para errores antes de la compilación.\n"
            "• **Guardar**: Guarda las configuraciones y cierra el editor.\n"
            "• **Cancelar**: Cierra sin guardar.\n"
            "• **Ayuda**: Abre esta ventana de ayuda.\n"
        ),  
        
    }
}

def show_help_window(parent, text, title="Help", language="en"):
    help_window = tk.Toplevel(parent)
    help_window.title(title)
    help_window.geometry("900x600")
    help_window.transient(parent)
    help_window.grab_set()

    # Language selection
    lang_frame = tk.Frame(help_window)
    lang_frame.pack(fill="x", padx=10, pady=5)
    tkstationary = tk.Label(lang_frame, text="Language:" if language == "en" else "Sprache:" if language == "de" else "Langue:" if language == "fr" else "Idioma:")
    lang_frame.pack(side="left")
    lang_var = tk.StringVar(value=language)
    tk.OptionMenu(lang_frame, lang_var, "en", "de", "fr", "es", command=lambda _: update_text(text_area, text, lang_var.get(), title)).pack(side="left")

    # Header
    header_label = tk.Label(help_window, text=title, font=("Arial", 14, "bold"), anchor="w")
    header_label.pack(fill="x", padx=10, pady=5)

    # Scrollable text area
    text_area = scrolledtext.ScrolledText(help_window, wrap=tk.WORD, font=("Courier", 10))
    text_area.insert(tk.END, text[language])
    text_area.configure(state="disabled")
    text_area.pack(expand=True, fill="both", padx=10, pady=5)

    # Close button
    close_button = tk.Button(help_window, text="Close" if language == "en" else "Schließen" if language == "de" else "Fermer" if language == "fr" else "Cerrar", command=help_window.destroy)
    close_button.pack(pady=10)

    def update_text(text_area, text, lang, base_title):
        text_area.configure(state="normal")
        text_area.delete(1.0, tk.END)
        text_area.insert(tk.END, text[lang])
        text_area.configure(state="disabled")
        close_button.config(text="Close" if lang == "en" else "Schließen" if lang == "de" else "Fermer" if lang == "fr" else "Cerrar")
        new_title = base_title
        if lang == "en":
            new_title = base_title.replace("Hilfe", "Help").replace("Aide", "Help").replace("Ayuda", "Help")
        elif lang == "de":
            new_title = base_title.replace("Help", "Hilfe").replace("Aide", "Hilfe").replace("Ayuda", "Hilfe")
        elif lang == "fr":
            new_title = base_title.replace("Help", "Aide").replace("Hilfe", "Aide").replace("Ayuda", "Aide")
        elif lang == "es":
            new_title = base_title.replace("Help", "Ayuda").replace("Hilfe", "Ayuda").replace("Aide", "Ayuda")
        help_window.title(new_title)
        lang_frame.children["!label"].config(text="Language:" if lang == "en" else "Sprache:" if lang == "de" else "Langue:" if lang == "fr" else "Idioma:")

def show_edit_helper(parent_window, language="en"):
    title = "Help – Editor" if language == "en" else "Hilfe – Editor" if language == "de" else "Aide – Éditeur" if language == "fr" else "Ayuda – Editor"
    show_help_window(parent_window, HELP_TEXTS["edit_helper"], title=title, language=language)

def show_main_helper(parent_window, language="en"):
    title = "Help – AutoPy++" if language == "en" else "Hilfe – AutoPy++" if language == "de" else "Aide – AutoPy++" if language == "fr" else "Ayuda – AutoPy++"
    show_help_window(parent_window, HELP_TEXTS["main_helper"], title=title, language=language)

def show_spec_helper(parent_window, language="en"):
    title = "Help – Spec-Editor" if language == "en" else "Hilfe – Spec-Editor" if language == "de" else "Aide – Éditeur Spec" if language == "fr" else "Ayuda – Editor Spec"
    show_help_window(parent_window, HELP_TEXTS["spec_helper"], title=title, language=language)

def show_nuitka_helper(parent_window, language="en"):
    title = "Help – Nuitka Compilation Editor" if language == "en" else "Hilfe – Nuitka Compilation Editor" if language == "de" else "Aide – Éditeur de Compilation Nuitka" if language == "fr" else "Ayuda – Editor de Compilación Nuitka"
    show_help_window(parent_window, HELP_TEXTS["nuitka_helper"], title=title, language=language)

# Example usage for testing
if __name__ == "__main__":
    root = tk.Tk()
    root.title("Test Window")
    tk.Button(root, text="Show Edit Help (EN)", command=lambda: show_edit_helper(root, "en")).pack(pady=5)
    tk.Button(root, text="Show Edit Help (DE)", command=lambda: show_edit_helper(root, "de")).pack(pady=5)
    tk.Button(root, text="Show Edit Help (FR)", command=lambda: show_edit_helper(root, "fr")).pack(pady=5)
    tk.Button(root, text="Show Edit Help (ES)", command=lambda: show_edit_helper(root, "es")).pack(pady=5)
    tk.Button(root, text="Show Main Help (EN)", command=lambda: show_main_helper(root, "en")).pack(pady=5)
    tk.Button(root, text="Show Main Help (DE)", command=lambda: show_main_helper(root, "de")).pack(pady=5)
    tk.Button(root, text="Show Main Help (FR)", command=lambda: show_main_helper(root, "fr")).pack(pady=5)
    tk.Button(root, text="Show Main Help (ES)", command=lambda: show_main_helper(root, "es")).pack(pady=5)
    tk.Button(root, text="Show Spec Help (EN)", command=lambda: show_spec_helper(root, "en")).pack(pady=5)
    tk.Button(root, text="Show Spec Help (DE)", command=lambda: show_spec_helper(root, "de")).pack(pady=5)
    tk.Button(root, text="Show Spec Help (FR)", command=lambda: show_spec_helper(root, "fr")).pack(pady=5)
    tk.Button(root, text="Show Spec Help (ES)", command=lambda: show_spec_helper(root, "es")).pack(pady=5)
    tk.Button(root, text="Show Nuitka Help (EN)", command=lambda: show_nuitka_helper(root, "en")).pack(pady=5)
    tk.Button(root, text="Show Nuitka Help (DE)", command=lambda: show_nuitka_helper(root, "de")).pack(pady=5)
    tk.Button(root, text="Show Nuitka Help (FR)", command=lambda: show_nuitka_helper(root, "fr")).pack(pady=5)
    tk.Button(root, text="Show Nuitka Help (ES)", command=lambda: show_nuitka_helper(root, "es")).pack(pady=5)
    root.mainloop()