LANGUAGES = {
    "de": {
        "title": "AutoPy++",
        "compile_a_col": "A",
        "compile_b_col": "B",
        "compile_c_col": "C",
        "name_col": "Name",
        "script_col": "Skriptpfad",
        "add_btn": "➕ Hinzufügen",
        "edit_btn": "✏️ Bearbeiten",
        "delete_btn": "🗑 Löschen",
        "save_btn": "💾 Speichern",
        "save_as_btn": "💾 Speichern als",
        "tooltip_save_btn": "💾 Speichert die aktuelle Projektliste (STRG+S).",
        "tooltip_save_as_btn": "💾 Speichert die Projektliste unter neuem Namen.",
        "load_btn": "📂 Lade",
        "clear_btn": "🆕 Neues Projekt",
        "clear_work_dir_btn": "🗑 Log löschen",
        "compile_all_btn": "🚀 Start Export",
        "extensions_btn": "⚙ Erweiterungen",
        "mode_a": "Modus A",
        "mode_b": "Modus B",
        "mode_c": "Modus C",
        "tooltip_compile_mode": "Aktiven Kompilier-Modus wählen (A oder B)",
        "status_ready": "💤",
        "error_no_entry": "Kein Eintrag ausgewählt.",
        "debug_btn": "🔎 Inspector",
        "about_btn": "ℹ️ Über",
        "tooltip_about_btn": "Zeigt Informationen über AutoPy++",
        "load_ini_btn": "⚙️ INI laden",
        "tooltip_load_ini_btn": "INI-Datei auswählen und überschreiben",
        "store_ini_popup_btn": "📤 INI exportieren",
        "load_ini_popup_btn": "📥 INI laden",
        "tooltip_extensions_btn": "Konfiguration externer Tools",
        "tooltip_debug_btn": "Öffnet den Debug-Inspector",
        "tooltip_save_project": "💾 Speichern.",
        "tooltip_cancel_project": "❌ Abbrechen.",
        "tooltip_add_btn": "➕ Fügt eine neue Datei (z. B. Python-Skript) zum Kompilieren hinzu.",
        "tooltip_edit_btn": "✏️ Bearbeitet die Einstellungen des ausgewählten Projekts.",
        "tooltip_delete_btn": "🗑️ Löscht das ausgewählte Projekt aus der Liste.",
        "tooltip_load_btn": "📂 Lädt eine Projektliste aus einer Datei.",
        "tooltip_clear_btn": "🆕 Entfernt alle Projekte aus der Liste.",
        "tooltip_clear_work_dir_btn": "🗑️ Löscht alle Logdateien (compile_*.log) im Arbeitsverzeichnis.",
        "tooltip_compile_all_btn": "🚀 Kompiliert alle ausgewählten Projekte gleichzeitig.",
        "tooltip_save_btn": "💾 Speichert die Projektliste als JSON oder ein Projekt als .spec-Datei.",
        "tooltip_load_ini_btn": "⚙️ INI-Datei auswählen und überschreiben",
        "status_toggle_compile": "Kompilieren für {name} {state}.",
        "status_project_added": "✅ Eintrag {name} hinzugefügt.",
        "status_entry_edited": "✅ Eintrag {name} bearbeitet.",
        "status_entry_deleted": "✅ Eintrag {name} gelöscht.",
        "status_saved": "✅ Einträge in {datei} gespeichert.",
        "status_loaded": "✅ Einträge aus {datei} geladen.",
        "status_error_no_entry": "❌ Fehler: Keine Einträge ausgewählt.",
        "status_error_invalid_json": "❌ Fehler: Ungültiges JSON.",
        "status_error_load": "❌ Fehler beim Laden.",
        "status_error_save": "❌ Fehler beim Speichern.",
        "success_compile": "✅ Alle ausgewählten Einträge wurden kompiliert.",
        "success_saved": "✅ Einträge wurden in {datei} gespeichert.",
        "success_loaded": "✅ Einträge aus {datei} geladen.",
        "status_spec_exported": "💾 .spec-Datei gespeichert: {path}",
        "status_error_export_spec": "❌ Fehler beim Speichern der .spec-Datei: {error}",
        "language_label": "🌐 Sprache:",
        "tooltip_toggle_design": "🌗 Zwischen Dunkel-/Hell-Modus wechseln",
        "spec_file_label": "📄 Spec-Datei:",
        "name_label": "Name:",
        "icon_label": "🖼 Iconpfad:",
        "add_data_label": "➕ Add-Data:",
        "hidden_imports_label": "🫥 Hidden Imports:",
        "version_label": "📜 Version-Datei:",
        "output_label": "📁 Ausgabeordner:",
        "onefile_label": "📦 Onefile",
        "windowed_label": "🪟 Fenster-Modus",
        "console_label": "💻 Konsole",
        "upx_label": "📦 UPX",
        "debug_label": "🐞 Debug",
        "options_label": "⚙️ Weitere Optionen:",
        "clean_label": "🧹 Clean",
        "strip_label": "✂️ Strip",
        "noupx_label": "🚫 No UPX",
        "runtime_hook_label": "🪝 Runtime Hook:",
        "splash_label": "🖼 Splash-Bild:",
    },
    "en": {
        "title": "AutoPy++",
        "compile_a_col": "A",
        "compile_b_col": "B",
        "compile_c_col": "C",
        "name_col": "Name",
        "script_col": "Script Path",
        "add_btn": "➕ Add",
        "edit_btn": "✏️ Edit",
        "delete_btn": "🗑 Delete",
        "save_btn": "💾 Save",
        "save_as_btn": "💾 Save as",
        "tooltip_save_btn": "💾 Save the current project list (CTRL+S).",
        "tooltip_save_as_btn": "💾 Save the project list under a new name.",
        "load_btn": "📂 Load",
        "clear_btn": "🆕 New Project",
        "clear_work_dir_btn": "🗑 Clear Logs",
        "compile_all_btn": "🚀 Start Export",
        "extensions_btn": "⚙ Extensions",
        "mode_a": "Mode A",
        "mode_b": "Mode B",
        "mode_c": "Mode C",
        "tooltip_compile_mode": "Select the active compilation mode (A or B)",
        "status_ready": "💤",
        "error_no_entry": "No entry selected.",
        "debug_btn": "🔎 Inspector",
        "about_btn": "ℹ️ About",
        "tooltip_about_btn": "Shows information about AutoPy++",
        "load_ini_btn": "⚙️ Load INI",
        "tooltip_load_ini_btn": "Select and overwrite INI file",
        "store_ini_popup_btn": "📤 Export INI",
        "load_ini_popup_btn": "📥 Load INI",
        "tooltip_extensions_btn": "Configure external tools",
        "tooltip_debug_btn": "Opens the debug inspector",
        "tooltip_save_project": "💾 Save.",
        "tooltip_cancel_project": "❌ Cancel.",
        "tooltip_add_btn": "➕ Adds a new file (e.g., Python script) for compilation.",
        "tooltip_edit_btn": "✏️ Edits the settings of the selected project.",
        "tooltip_delete_btn": "🗑️ Deletes the selected project from the list.",
        "tooltip_load_btn": "📂 Loads a project list from a file.",
        "tooltip_clear_btn": "🆕 Removes all projects from the list.",
        "tooltip_clear_work_dir_btn": "🗑️ Deletes all log files (compile_*.log) in the workdir.",
        "tooltip_compile_all_btn": "🚀 Compiles all selected projects simultaneously.",
        "tooltip_load_ini_btn": "⚙️ Select and overwrite INI file",
        "status_toggle_compile": "Compile for {name} {state}.",
        "status_project_added": "✅ Entry {name} added.",
        "status_entry_edited": "✅ Entry {name} edited.",
        "status_entry_deleted": "✅ Entry {name} deleted.",
        "status_saved": "✅ Entries saved to {datei}.",
        "status_loaded": "✅ Entries loaded from {datei}.",
        "status_error_no_entry": "❌ Error: No entries selected.",
        "status_error_invalid_json": "❌ Error: Invalid JSON.",
        "status_error_load": "❌ Error loading file.",
        "status_error_save": "❌ Error saving file.",
        "success_compile": "✅ All selected entries have been compiled.",
        "success_saved": "✅ Entries saved to {datei}.",
        "success_loaded": "✅ Entries loaded from {datei}.",
        "status_spec_exported": "💾 .spec file saved: {path}",
        "status_error_export_spec": "❌ Error saving .spec file: {error}",
        "language_label": "🌐 Language:",
        "tooltip_toggle_design": "🌗 Toggle dark/light mode",
        "spec_file_label": "📄 Spec File:",
        "name_label": "Name:",
        "icon_label": "🖼 Icon Path:",
        "add_data_label": "➕ Add-Data:",
        "hidden_imports_label": "🫥 Hidden Imports:",
        "version_label": "📜 Version File:",
        "output_label": "📁 Output Folder:",
        "onefile_label": "📦 Onefile",
        "windowed_label": "🪟 Windowed Mode",
        "console_label": "💻 Console",
        "upx_label": "📦 UPX",
        "debug_label": "🐞 Debug",
        "options_label": "⚙️ Additional Options:",
        "clean_label": "🧹 Clean",
        "strip_label": "✂️ Strip",
        "noupx_label": "🚫 No UPX",
        "runtime_hook_label": "🪝 Runtime Hook:",
        "splash_label": "🖼 Splash Image:",
    }
}
